# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_openid_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useropenid',
            options={'permissions': (('account_verified', 'The OpenID has been verified'),)},
        ),
    ]
