# Generated by Django 2.2.11 on 2020-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openid_auth', '0002_auto_20160106_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useropenid',
            name='claimed_id',
            field=models.TextField(max_length=2047),
        ),
    ]
