# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 08:12
from __future__ import unicode_literals


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cog', '0003_project_nodeswidgetenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(blank=True, help_text=b'Short index label', max_length=28, null=True, verbose_name=b'Label'),
        ),
    ]
