# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 10:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cog', '0005_project_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
