# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-26 03:39
from __future__ import unicode_literals


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cog', '0008_auto_20160609_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='project',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='project',
            name='forumNotificationEnabled',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='ForumThread',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
    ]
