# Generated by Django 2.2.11 on 2020-03-24 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cog', '0009_auto_20160826_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='institution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='researchKeywords',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='communicationmeans',
            name='frequency',
            field=models.CharField(blank=True, help_text='String used to describe the frequency of the meeting (e.g. Weekly on Wednesdays, Monthly, Yearly, ...).', max_length=50, null='True', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='communicationmeans',
            name='membership',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('By Invitation', 'By Invitation')], help_text='A field that indicates whether the means is open or closed to non-members.', max_length=50, null=True, verbose_name='Membership'),
        ),
        migrations.AlterField(
            model_name='communicationmeans',
            name='participationDetails',
            field=models.TextField(blank=True, help_text='Information about how a person would participate: phone number, pass code, meeting venue, etc.', null=True, verbose_name='Participation Details'),
        ),
        migrations.AlterField(
            model_name='communicationmeans',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Overall Project Coordination', 'Overall Project Coordination'), ('Steering Committee', 'Steering Committee'), ('Design', 'Design'), ('Design and Implementation Review', 'Design and Implementation Review'), ('Task Prioritization', 'Task Prioritization'), ('Requirements Identification', 'Requirements Identification'), ('Strategic Direction', 'Strategic Direction'), ('External Review', 'External Review'), ('Implementation', 'Implementation'), ('Meeting Planning', 'Meeting Planning'), ('Testing', 'Testing'), ('Knowledge Transfer', 'Knowledge Transfer'), ('Grant Writing', 'Grant Writing'), ('Other', 'Other')], help_text='Purpose of meeting (choose from controlled vocabulary).', max_length=50, null=True, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='communicationmeans',
            name='title',
            field=models.CharField(help_text='String used to describe the name of the meeting.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='communicationmeans',
            name='type',
            field=models.CharField(choices=[('Telco', 'Telco'), ('Face-to-face', 'Face-to-face'), ('Webinar', 'Webinar'), ('Video Conference', 'Video Conference'), ('Internet Chat', 'Internet Chat'), ('Wiki', 'Wiki'), ('Mailing List', 'Mailing List')], help_text='String used to describe the type of meeting (choose from controlled vocabulary).', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='datacartitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private?'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='externalurl',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='externalurl',
            name='type',
            field=models.CharField(choices=[('blog', 'Blog'), ('repository', 'Repositories'), ('homepage', 'Home Page'), ('reference', 'Reference'), ('tracker', 'Trackers'), ('usecase', 'Use Cases'), ('policy', ' Policies'), ('roadmaps', 'Roadmaps'), ('download', 'Download / Releases'), ('admin_docs', 'Install / Admin Docs'), ('user_docs', 'User Docs'), ('faq', 'FAQ'), ('code_example', 'Code Examples'), ('dev_docs', 'Dev Docs'), ('testing', 'Testing'), ('checklist', 'Checklists'), ('prioritization', 'Prioritization'), ('metric', 'Metrics'), ('release_schedule', 'Release Schedules')], max_length=20, verbose_name='URL Type'),
        ),
        migrations.AlterField(
            model_name='externalurl',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='name',
            field=models.CharField(help_text='Organization or agency that financially supports the project', max_length=200),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='url',
            field=models.URLField(blank=True, help_text='Funding Source URL', null=True),
        ),
        migrations.AlterField(
            model_name='lock',
            name='object_id',
            field=models.IntegerField(verbose_name='Object Identifier'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='object_type',
            field=models.CharField(max_length=100, verbose_name='Object Type'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update Date'),
        ),
        migrations.AlterField(
            model_name='loggedevent',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time'),
        ),
        migrations.AlterField(
            model_name='managementbody',
            name='category',
            field=models.CharField(blank=True, choices=[('Strategic', 'Strategic'), ('Operational', 'Operational')], default='Strategic', help_text='Strategic or Operational management body purpose.', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='managementbody',
            name='description',
            field=models.TextField(help_text='A short description providing extra information about organizational body.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='managementbody',
            name='other',
            field=models.CharField(blank=True, help_text='Specify any other purpose(s) not included in the controlled vocabulary.', max_length=200, null=True, verbose_name='Other Purpose'),
        ),
        migrations.AlterField(
            model_name='managementbody',
            name='termsOfReference',
            field=models.TextField(blank=True, help_text='A description of the duties and responsibilities of the organizational body.', verbose_name='Terms of Reference'),
        ),
        migrations.AlterField(
            model_name='managementbody',
            name='title',
            field=models.CharField(help_text='String used to succinctly describe an organizational body.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='managementbodypurpose',
            name='category',
            field=models.CharField(choices=[('Strategic', 'Strategic'), ('Operational', 'Operational')], default='Strategic', help_text='Strategic or Operational management body purpose.', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='managementbodypurpose',
            name='purpose',
            field=models.CharField(choices=[('Strategic Direction', ' Strategic Direction (Strategic)'), ('Advice or Guidance', ' Advice or Guidance (Strategic)'), ('Program Direction', ' Program Direction (Strategic)'), ('Review', ' Review (Strategic)'), ('Research', ' Research (Operational)'), ('Development', ' Development (Operational)'), ('Requirements Identification', ' Requirements Identification (Operational)'), ('Task Prioritization', ' Task Prioritization (Operational)'), ('Testing', ' Testing (Operational)'), ('Review', ' Review (Operational)'), ('Meeting and Event Planning', ' Meeting and Event Planning (Operational)'), ('Administration', ' Administration (Operational)')], default='Other', help_text='Type of organizational body (choose from controlled vocabulary).', max_length=50, verbose_name='Purpose/Role'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='other_projects',
            field=models.ManyToManyField(blank=True, related_name='other_news', to='cog.Project', verbose_name='Projects Notified'),
        ),
        migrations.AlterField(
            model_name='news',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cog.Project', verbose_name='About Project'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Project or organization that collaborates on this project', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, help_text='Organization URL', null=True),
        ),
        migrations.AlterField(
            model_name='organizationalrole',
            name='category',
            field=models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Member', 'Member')], default='Member', help_text='Lead or Member role.', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='organizationalrole',
            name='description',
            field=models.TextField(blank=True, help_text='Long description providing extra information about an organizational role.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organizationalrole',
            name='title',
            field=models.CharField(blank=True, help_text='Optional string used to succinctly describe an organizational role.', max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='organizationalrole',
            name='type',
            field=models.CharField(choices=[('Principal Investigator', ' Principal Investigator (Lead Role)'), ('Co-Investigator', ' Co-Investigator (Lead Role)'), ('Program Manager', ' Program Manager (Lead Role)'), ('Project Manager', ' Project Manager (Lead Role)'), ('Software Architect', ' Software Architect (Lead Role)'), ('Lead', ' Lead (Lead Role)'), ('Other Lead', ' Other Lead (Lead Role)'), ('', '--------------'), ('Administrative Assistant', ' Administrative Assistant (Member Role)'), ('Data Manager', ' Data Manager (Member Role)'), ('Outreach Coordinator', ' Outreach Coordinator (Member Role)'), ('Researcher', ' Researcher (Member Role)'), ('Software Developer', ' Software Developer (Member Role)'), ('Webmaster', ' Webmaster (Member Role)'), ('Other Member', ' Other Member (Member Role)')], default='', help_text='Type of organizational role (choose from controlled vocabulary).', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='docs',
            field=models.ManyToManyField(blank=True, to='cog.Doc', verbose_name='Attachments'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Is Home Page?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_restricted',
            field=models.BooleanField(default=False, verbose_name='Restricted?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(blank=True, help_text='Short index label', max_length=28, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cog.Post', verbose_name='Parent Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='template',
            field=models.CharField(blank=True, max_length=200, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('blog', 'Blog'), ('page', 'Page'), ('hyperlink', 'Hyperlink'), ('notes', 'Notes')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bindingLanguage',
            field=models.TextField(blank=True, help_text='The binding language(s) of the software code.', null=True, verbose_name='Binding Language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dataSearchEnabled',
            field=models.BooleanField(default=False, help_text='Enable data search?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='A short paragraph that describes the project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='developmentOverview',
            field=models.TextField(blank=True, help_text='One or more paragraphs providing a general overview of the development processes for the project.', null=True, verbose_name='Development Overview'),
        ),
        migrations.AlterField(
            model_name='project',
            name='externalDependencies',
            field=models.TextField(blank=True, help_text='The major libraries and packages the software depends on.', null=True, verbose_name='External Dependencies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_homepage',
            field=models.URLField(blank=True, help_text='External Home Page', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='getInvolved',
            field=models.TextField(blank=True, help_text='Describe how to participate in the project.', null=True, verbose_name='Get Involved'),
        ),
        migrations.AlterField(
            model_name='project',
            name='getting_started',
            field=models.TextField(blank=True, help_text='Describe how users can get started with this project.', null=True, verbose_name='Getting Started'),
        ),
        migrations.AlterField(
            model_name='project',
            name='governanceOverview',
            field=models.TextField(blank=True, help_text='One or more paragraphs providing a general overview of the governance structure for the project.', null=True, verbose_name='Governance Overview'),
        ),
        migrations.AlterField(
            model_name='project',
            name='history',
            field=models.TextField(blank=True, help_text='A narrative describing the origination and evolution of the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementationLanguage',
            field=models.TextField(blank=True, help_text='The implementation language(s) of the software code.', null=True, verbose_name='Implementation Language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='license',
            field=models.TextField(blank=True, help_text='Name of license used for the software, if any.', null=True, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Optional logo hyperlink URL.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_name',
            field=models.CharField(help_text='Fully spelled project name.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='maxUploadSize',
            field=models.IntegerField(blank=True, default=52428800, help_text='Maximum upload size in bytes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='meetingSupport',
            field=models.TextField(blank=True, help_text='Describe how to setup meetings.', null=True, verbose_name='Meeting Support'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mission',
            field=models.TextField(blank=True, help_text='Succinctly describes why the project exists and what it does.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nodesWidgetEnabled',
            field=models.BooleanField(default=False, help_text='Enable federated nodes widget ?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectContacts',
            field=models.TextField(blank=True, default='', help_text='Describe how to contact the project.', null=True, verbose_name='Project Contacts'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirementsIdentificationProcess',
            field=models.TextField(blank=True, help_text='A paragraph describing how requirements are identified. This description may include who participates, what system is used to track requirements, and whether the results are public.', null=True, verbose_name='Requirements Identification Process'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(help_text="Short project acronym, 20 characters maximum, use only letters, numbers and '_', '-', no spaces.", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='software_features',
            field=models.TextField(blank=True, help_text=None, null=True, verbose_name='Software Features'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supportedPlatforms',
            field=models.TextField(blank=True, help_text='The computing platforms that the software can run on.', null=True, verbose_name='Supported Platforms'),
        ),
        migrations.AlterField(
            model_name='project',
            name='system_requirements',
            field=models.TextField(blank=True, help_text=None, null=True, verbose_name='Software System Requirements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='taskPrioritizationStrategy',
            field=models.TextField(blank=True, help_text='A paragraph describing how tasks are prioritized. This description may include who participates, how often they meet, how they meet, and whether the results are public.', null=True, verbose_name='Task Prioritization Strategy.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technicalSupport',
            field=models.TextField(blank=True, help_text='Email address for technical questions.', null=True, verbose_name='Technical Support'),
        ),
        migrations.AlterField(
            model_name='project',
            name='values',
            field=models.TextField(blank=True, help_text='Beliefs that are shared among the members of a project. Values influence culture and priorities and provide a framework for informing decisions.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vision',
            field=models.TextField(blank=True, help_text='Outlines what a project wants to be, or how it wants the world in which it operates to be. It is a long-term view.'),
        ),
        migrations.AlterField(
            model_name='projectimpact',
            name='description',
            field=models.TextField(help_text='Describe a major impact of this project in its field.', verbose_name='Project Impact'),
        ),
        migrations.AlterField(
            model_name='projectimpact',
            name='title',
            field=models.CharField(default='', help_text='Title for this impact.', max_length=200),
        ),
        migrations.AlterField(
            model_name='projecttab',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='searchgroup',
            name='name',
            field=models.CharField(default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='constraints',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this project search capabilities.', null=True, verbose_name='Search Help'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_password_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time when Password was Last Updated'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Do NOT list me among project members'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='researchInterests',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='researchKeywords',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscribed',
            field=models.BooleanField(default=True, verbose_name='Subscribe to COG mailing list?'),
        ),
        migrations.AlterField(
            model_name='userurl',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
    ]
